Extract DUT devices UUID
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>

diff --git a/.github/workflows/balena.yml b/.github/workflows/balena.yml
--- a/.github/workflows/balena.yml
+++ b/.github/workflows/balena.yml
@@ -75,6 +75,13 @@ jobs:
             | jq -r '.d[].id')
           echo "::set-output name=balena_dut_id::${dut_id}"
 
+          dut_uuid=$(curl --silent --retry ${{ env.RETRY }} -o /dev/null \
+            'https://api.${{ env.ENVIRONMENT }}/v6/device?$top=1&$select=id&$filter=belongs_to__application%20eq%20(${app_id})%20and%20device_tag/any(dt:dt/tag_key%20eq%20%27dut:${{ env.DEVICE_TYPE }}%27)' \
+            -H 'authorization: Bearer ${{ secrets.BALENACLOUD_API_KEY }}' \
+            -H 'content-type: application/json' \
+            | jq -r '.d[].uuid')
+          echo "::set-output name=balena_dut_uuid::${dut_uuid}"
+
       # https://github.com/balena-io/balena-cli/issues/1543
       - name: pin DUT device to draft release
         id: pin-device
@@ -122,3 +129,44 @@ jobs:
               ((retry_count++))
             fi
           done
+
+      # - name: Can we stream the logs from the SUT container (Stretch goals)
+      #   id: sut-container-status
+      #   if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed'}}
+      #   run: |
+
+      # (TBC) additional overrides for testing (i.e. DB_USER, DB_PASSWORD, etc.)
+      # - name: Poll for SUT container STATUS
+      #   id: sut-container-status
+      #   if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed'}}
+      #   run: |
+
+      # - name: Poll for SUT container STATUS
+      #   id: sut-container-status
+      #   if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed'}}
+      #   run: |
+
+      #   while true; do
+      #     set -uae
+      #     result = curl -X GET --silent --retry ${{ env.RETRY }} --fail -o /dev/null \
+      #     'https://api.balena-cloud.com/v6/release_tag?\$filter=release/commit%20eq%20${{ steps.push-release.outputs.release_id }}' \
+      #     -H 'Content-Type: application/json' \
+      #     -H 'Authorization: Bearer ${{ secrets.BALENACLOUD_API_KEY }}'
+
+      #     if result === '"success"'; then
+      #       echo "::set-output name=sut_container_status::success"
+      #     else
+      #       echo "::set-output name=sut_container_status::failure"
+      #     fi
+      #   done
+
+      # - name: MARK THE RELEASE WITH EXIT CODE
+      #   id: generate-compose
+      #   if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed'}}
+      #   run: OUR DOCKER COMPOSE GENERATOR
+
+
+      # - name: PASS/FAIL the release
+      #   id: generate-compose
+      #   if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed'}}
+      #   run: OUR DOCKER COMPOSE GENERATOR
